global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@vibecode.com'
  slack_api_url: '${SLACK_WEBHOOK_URL}'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'

  - name: 'critical-alerts'
    email_configs:
      - to: '${ALERT_EMAIL}'
        subject: 'CRITICAL: Vibe Code Alert - {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}

          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          {{ end }}

          Dashboard: http://grafana:3000/d/vibe-code
    slack_configs:
      - channel: '#alerts'
        title: 'CRITICAL: Vibe Code Alert'
        text: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}

          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          {{ end }}

  - name: 'warning-alerts'
    email_configs:
      - to: '${ALERT_EMAIL}'
        subject: 'WARNING: Vibe Code Alert - {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}

          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          {{ end }}
    slack_configs:
      - channel: '#monitoring'
        title: 'WARNING: Vibe Code Alert'
        text: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}

          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
